### ISSUE TITLE
cl-lib-2.0

### ISSUE THREAD

**Issue by henrymazza** [DarwinAwardWinner/osx-pseudo-daemon#3]
`An error occurred while installing mac-pseudo-daemon (error: (error Need package ‘cl-lib-2.0’, but only 0.6.1 is available))`

I don't think this package exists at all.

**Comment by DarwinAwardWinner** [comment]
That's weird. I'm not sure where I got 2.0 from. I'll fix it tonight.

**Comment by henrymazza** [comment]
Great!


On 26 July 2017 at 18:30:38, Ryan C. Thompson (notifications@github.com)
wrote:

That's weird. I'm not sure where I got 2.0 from. I'll fix it tonight.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DarwinAwardWinner/osx-pseudo-daemon/issues/3#issuecomment-318188637>,
or mute the thread

**Comment by DarwinAwardWinner** [comment]
Closed by 2b5b467. (The auto-close message that disagrees with this was from an accidental force push. Disregard it.)
